config/routes.rb
Hanabi::Application.routes.draw do

  get "users/new"

  root to: 'pages#home'
  match '/about',   to: 'pages#about'
  match '/contact',   to: 'pages#contact'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def faq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Hanabi"
    if page_title.empty?
      base_title
    else
      "#{base_title}|#{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small Powered by noodles!
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li= link_to "FAQ", faq_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Hanabi", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "About", about_path
          %li= link_to "Contact", contact_path
          %li= link_to "Sign in", "#"

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ :src => 'http://html5shim.googlecode.com/svn/trunk/html5.js' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all"
    / Note used to be :media => "all" in Ruby 1.8
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    %div.container
      = yield
      = render 'layouts/footer'

app/views/pages/about.html.haml
- provide(:title, 'About')
%h1 About Us
%p About page

app/views/pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact Us
%p Contact page.

app/views/pages/faq.html.haml
- provide(:title, 'FAQ')
%h1 FAQ
%p FAQ page.

app/views/pages/home.html.haml
.center.hero-unit
  %h1 Hanabi Solutions
  %h2 This is the home page.
  =link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"
=link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
%p Find me in app/views/users/new.html.erb